import { test } from 'node:test';
import assert from 'node:assert/strict';
import { renderGlobalEnv, formatEnvValue } from '../public/scripts/global-env.js';
import { SCHEMA_URL_V3 } from '../public/scripts/resolver.js';

const ISO = '2026-06-19T10:00:00.000Z';
const FIXED_NOW = '2026-06-19T12:00:00.000Z';

function vaultWith(shared) {
  return {
    $schema: SCHEMA_URL_V3,
    version: 3,
    shared,
    projects: {},
    metadata: { updated_at: ISO },
  };
}

test('renderGlobalEnv — header is fixed 2-line block per §5.1', () => {
  const out = renderGlobalEnv(vaultWith({}), { now: FIXED_NOW });
  const lines = out.split('\n');
  assert.equal(lines[0], `# Generated by envpact (global) on ${FIXED_NOW}`);
  assert.equal(lines[1], '# DO NOT COMMIT — managed by envpact');
  assert.equal(lines[2], '');
});

test('renderGlobalEnv — walks shared keys alphabetically', () => {
  const out = renderGlobalEnv(vaultWith({
    ZEBRA: { value: 'last', _modified_at: ISO },
    APPLE: { value: 'first', _modified_at: ISO },
    MANGO: { value: 'middle', _modified_at: ISO },
  }), { now: FIXED_NOW });
  const body = out.split('\n').slice(3).filter(Boolean);
  assert.deepEqual(body, ['APPLE=first', 'MANGO=middle', 'ZEBRA=last']);
});

test('renderGlobalEnv — encrypted entries become commented decrypt-via-cli lines', () => {
  const out = renderGlobalEnv(vaultWith({
    PLAIN: { value: 'visible', _modified_at: ISO },
    SECRET: { value: 'enc:Y2lwaGVy', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.match(out, /^PLAIN=visible$/m);
  assert.match(out, /^# SECRET: encrypted — decrypt-via-cli$/m);
  // Encrypted ciphertext MUST NOT appear in the output.
  assert.ok(!out.includes('Y2lwaGVy'));
});

test('renderGlobalEnv — invalid entries become "invalid entry" comments', () => {
  const out = renderGlobalEnv(vaultWith({
    BAD: { _modified_at: ISO },          // missing value
    WORSE: 'bare-string',                // not an object
    ALRIGHT: { value: 'ok', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.match(out, /^# BAD: invalid entry$/m);
  assert.match(out, /^# WORSE: invalid entry$/m);
  assert.match(out, /^ALRIGHT=ok$/m);
});

test('renderGlobalEnv — values with whitespace get double-quoted (§5)', () => {
  const out = renderGlobalEnv(vaultWith({
    SPACED: { value: 'has spaces here', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.match(out, /^SPACED="has spaces here"$/m);
});

test('renderGlobalEnv — values with # or = get quoted', () => {
  const out = renderGlobalEnv(vaultWith({
    HASH: { value: 'pound#sign', _modified_at: ISO },
    EQ: { value: 'a=b', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.match(out, /^HASH="pound#sign"$/m);
  assert.match(out, /^EQ="a=b"$/m);
});

test('renderGlobalEnv — backslashes and quotes are escaped inside quoted form', () => {
  const out = renderGlobalEnv(vaultWith({
    PATH: { value: 'C:\\Users\\me', _modified_at: ISO },
    QUOTED: { value: 'he said "hi" today', _modified_at: ISO },
  }), { now: FIXED_NOW });
  // backslash in input → escaped backslash in quoted output AND it
  // also has spaces so it gets quoted via the whitespace rule.
  assert.match(out, /^QUOTED="he said \\"hi\\" today"$/m);
  // PATH has no whitespace but backslash forces quoting:
  assert.match(out, /^PATH="C:\\\\Users\\\\me"$/m);
});

test('renderGlobalEnv — empty string value is quoted as ""', () => {
  const out = renderGlobalEnv(vaultWith({
    EMPTY: { value: '', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.match(out, /^EMPTY=""$/m);
});

test('renderGlobalEnv — leading whitespace is quoted', () => {
  const out = renderGlobalEnv(vaultWith({
    LEADING: { value: ' indented', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.match(out, /^LEADING=" indented"$/m);
});

test('renderGlobalEnv — empty vault produces just the header + trailing newline', () => {
  const out = renderGlobalEnv({ shared: {} }, { now: FIXED_NOW });
  const expected =
    `# Generated by envpact (global) on ${FIXED_NOW}\n` +
    '# DO NOT COMMIT — managed by envpact\n' +
    '\n';
  assert.equal(out, expected);
});

test('renderGlobalEnv — output ends with a trailing newline', () => {
  const out = renderGlobalEnv(vaultWith({
    K: { value: 'v', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.equal(out[out.length - 1], '\n');
});

test('renderGlobalEnv — never emits raw enc: ciphertext', () => {
  // Canary: the Download .env button must never put ciphertext in
  // the file — the decryption stays a CLI-only operation.
  const out = renderGlobalEnv(vaultWith({
    A: { value: 'enc:AAAA', _modified_at: ISO },
    B: { value: 'enc:BBBB', _modified_at: ISO },
    C: { value: 'plain', _modified_at: ISO },
  }), { now: FIXED_NOW });
  assert.ok(!out.includes('enc:AAAA'));
  assert.ok(!out.includes('enc:BBBB'));
  assert.match(out, /^C=plain$/m);
});

test('formatEnvValue — bare value has no quotes', () => {
  assert.equal(formatEnvValue('simple'), 'simple');
  assert.equal(formatEnvValue('123'), '123');
});

test('formatEnvValue — special chars trigger quoting', () => {
  assert.equal(formatEnvValue(''), '""');
  assert.equal(formatEnvValue('with space'), '"with space"');
  assert.equal(formatEnvValue('a"b'), '"a\\"b"');
});
